import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ReportService } from '../report-service.service';
import { Patient } from '../patient';
import { Report } from '../report';

@Component({
  selector: 'app-reports',
  standalone: false,
  templateUrl: './reports.component.html',
  styleUrls: ['./reports.component.css'],
})
export class ReportsComponent implements OnInit {
  reports!: Report | number;
  patient!: Patient;
  totalReports: number = 0;
  doctorId: number = 1; // Replace with actual logged-in doctor's ID

  constructor(
    private route: ActivatedRoute,
    private reportService: ReportService
  ) {}

  ngOnInit(): void {
    const patientId = Number(this.route.snapshot.paramMap.get('patientId'));
    if (patientId) {
      this.loadReports(patientId);
    }

    this.loadReportCount();
  }

  loadReports(patientId: number) {
    this.reportService.countReportsByDoctorId(patientId).subscribe(
      (data) => {
        this.reports = data;
        console.log('Reports for patient:', data);
      },
      (error) => console.error('Error fetching reports:', error)
    );
  }

  loadReportCount() {
    this.reportService.countReportsByDoctorId(this.doctorId).subscribe(
      (count) => {
        this.totalReports = count;
        console.log('Total Reports Generated by Doctor:', count);
      },
      (error) => console.error('Error fetching report count:', error)
    );
  }
}
